services:
  bot:
    build: 
      context: .
      network: host
    environment:
      - DISCORD_BOT_TOKEN=YOUR_TOKEN
      - OPENAI_API_KEY=YOUR_TOKEN
      - GUILD_ID=YOUR_SERVER_ID
      - BOT_PREFIX=/